# -*- coding: utf-8 -*-
"""movieinternshipproject.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rlJPnI5WKubCTbSRRFWR9y-pzoCBNvLK

MOVIE RECOMMENDATION SYSTEM

To develop a recommender system that pridicts or filters according to the user's choices using Collaborative filtering and Content-based filtering

IMPORT LIBRARY
"""

import pandas as pd

import numpy as np

"""IMPORT DATASET"""

df=pd.read_csv('https://raw.githubusercontent.com/YBI-Foundation/Dataset/main/Movies%20Recommendation.csv')

df.head()

df.info()

df.shape

df.columns

"""GET FEATURE SELECTION"""

df_features=df[['Movie_Genre','Movie_Keywords','Movie_Tagline','Movie_Cast','Movie_Director']].fillna('')

df_features.shape

df_features

x = df_features['Movie_Genre'] + ' ' + df_features['Movie_Keywords'] + ' ' + df_features['Movie_Tagline'] + ' ' + df_features['Movie_Cast'] + ' ' + df_features['Movie_Director']

x

x.shape

"""GET FEATURE TEXT CONVERSION TO TOKENS"""

from sklearn.feature_extraction.text import TfidfVectorizer

tfidf=TfidfVectorizer()

x=tfidf.fit_transform(x)

x.shape

print(x)

"""GETING SIMILARITY SCORE USING COSINE SIMILARITY

"""

from sklearn.metrics.pairwise import cosine_similarity

Similarity_Score=cosine_similarity(x)

Similarity_Score

Similarity_Score.shape

"""MOVIE NAME AS INPUT FROM USER AND VALIDATE FOR THE CLOSEST SPELLING"""

Favourite_Movie_Name=input('Enter you favourite movie name : ')

All_Moies_Title_List=df['Movie_Title'].tolist()

import difflib

Movie_Recommendation = difflib.get_close_matches(Favourite_Movie_Name, All_Moies_Title_List)
print(Movie_Recommendation)

Close_Match = Movie_Recommendation[0]
print(Close_Match)

Index_of_Close_Match_Movie = df[df.Movie_Title == Close_Match]['Movie_ID'].values[0]
print(Index_of_Close_Match_Movie)

Recommendation_Score = list(enumerate(Similarity_Score[Index_of_Close_Match_Movie]))
print(Recommendation_Score)

len(Recommendation_Score)

"""SORTING BASED ON RECOMMENDATION SCORE

---


"""

Sorted_Similar_Movies=sorted(Recommendation_Score, key = lambda x:x[1], reverse=True)
print(Sorted_Similar_Movies)

print('Top 30 Movies Suggested for You : \n')

i = 1
for movie in Sorted_Similar_Movies:
  index = movie[0]
  title_from_index = df[df.index==index]['Movie_Title'].values[0]
  if (i<31):
    print(i, '.',title_from_index)
    i+=1

"""TOP 10 MOVIE RECOMMENDATION"""

Movie_Name = input('Enter Your Favourite Movie Name: ')

list_of_all_titles = df['Movie_Title'].tolist()

Find_Close_Match = difflib.get_close_matches(Movie_Name, list_of_all_titles)

Close_Match = Find_Close_Match[0]

Index_of_Movie = df[df.Movie_Title == Close_Match]['Movie_ID'].values[0]

Recommendation_Score = list(enumerate(Similarity_Score[Index_of_Movie]))

sorted_similar_movies = sorted(Recommendation_Score, key = lambda x:x[1], reverse = True)

print('Top 10 Movies Suggested For You : \n')

i = 1
for movie in Sorted_Similar_Movies:
  index = movie[0]
  title_from_index = df[df.Movie_ID==index]['Movie_Title'].values
  if (i<11):
    print(i, '.',title_from_index)
    i+=1